// js/cases.js
export const cases = [
    { bab: 1, title: "Kasus #1: Pelacakan Sinyal", workspace: 'peta', briefing: "Intelijen kita mencegat dua sinyal terenkripsi, Detektif. Tim siber melacak jalur pergerakannya di seluruh kota. Sinyal Alpha bergerak lurus di jalur pertama, dan Sinyal Beta di jalur kedua.\n\nMisi Anda adalah memprediksi di mana kedua jalur ini akan bersilangan. Itu adalah lokasi pertemuan rahasia yang harus kita gagalkan!", eq: ['y = 2x + 3', 'y = -x + 9'], sol: { x: 2, y: 7 }, hint: "Gambarkan kedua garis di peta. Titik di mana mereka bertemu adalah jawabannya. Perhatikan baik-baik koordinat perpotongannya." },
    { bab: 1, title: "Kasus #2: Resep Rahasia", workspace: 'substitusi', briefing: "Koki terkenal di kota kehilangan resep legendarisnya! Brankasnya hanya bisa dibuka dengan dua variabel: jumlah 'x' gram rempah rahasia dan 'y' ml sari buah langka. Dua asistennya memberikan petunjuk.\n\nAsisten pertama bilang, 'Jumlah gram rempah (x) adalah dua kali lipat jumlah sari buah (y) dikurangi satu.'\nAsisten kedua berkata, 'Tiga kali jumlah rempah ditambah dua kali jumlah sari buah totalnya 19.'\n\nTemukan nilai x dan y untuk menyelamatkan resep itu!", eq: ['x = 2y - 1', '3x + 2y = 19'], sol: { x: 4.5, y: 2.75 }, hint: "Satu persamaan sudah dalam bentuk 'x = ...'. Klik blok kuning untuk mensubstitusikannya ke variabel x di persamaan kedua." },
    { bab: 1, title: "Kasus #3: Perang Harga", workspace: 'eliminasi', briefing: "Kekacauan terjadi di Pasar Logika. Dua pedagang, Pak Budi dan Pak Tono, menjual Apel (x) dan Jeruk (y) dengan harga misterius.\n\nSeorang pembeli berkata, 'Saya membeli 2 Apel dan 3 Jeruk seharga 12.000.'\nPembeli lain menambahkan, 'Aneh, saya beli 2 Apel dan 1 Jeruk harganya 8.000.'\n\nBerapa harga 1 Apel (x) dan 1 Jeruk (y) sebenarnya?", eq: ['2x + 3y = 12000', '2x + 1y = 8000'], sol: { x: 3000, y: 2000 }, hint: "Koefisien '2x' sudah sama. Coba kalikan salah satu persamaan dengan -1, lalu tekan tombol eliminasi." },
    { bab: 1, title: "Kasus #4: Drone Paralel", workspace: 'peta', briefing: "Peringatan keamanan! Dua drone pengintai tak dikenal terbang di atas kota. Menurut data radar, jalur terbang mereka sejajar sempurna.\n\nJika mereka terus terbang lurus, apakah ada kemungkinan mereka akan bertabrakan atau bertemu di satu titik? Jawabannya akan menentukan tingkat siaga kita.", eq: ['y = 0.5x + 2', 'y = 0.5x - 3'], sol: null, hint: "Dua garis yang sejajar memiliki gradien (kemiringan) yang sama. Bisakah mereka berpotongan?" },
    { bab: 1, title: "Kasus #5: Bayangan Ganda", workspace: 'peta', briefing: "Seorang informan misterius memberi kita dua petunjuk untuk melacak target. Petunjuk pertama adalah 'x + y = 5'. Sejam kemudian, petunjuk kedua datang: '2x + 2y = 10'.\n\nAnehnya, saat tim kita memplotnya di peta, kedua petunjuk itu menunjuk ke jalur yang sama persis! Apa artinya ini? Di mana saja target bisa berada?", eq: ['x + y = 5', '2x + 2y = 10'], sol: Infinity, hint: "Jika persamaan kedua disederhanakan (dibagi 2), apakah ia menjadi identik dengan persamaan pertama? Jika ya, artinya kedua petunjuk menunjuk ke satu garis yang sama." },
    { bab: 1, title: "Kasus #6: Jebakan Dalang", workspace: 'eliminasi', briefing: "INI DIA! Pesan langsung dari sang 'Dalang Persamaan'! Dia menantang kita secara langsung.\n\n'Detektif, aku tinggalkan teka-teki terakhir untuk Babak Pertama. Selesaikan jika kau bisa: 7x - y = 20 dan 3x + y = 10.'\n\nDia pikir kita tidak bisa memecahkannya. Buktikan dia salah!", eq: ['7x - y = 20', '3x + y = 10'], sol: { x: 3, y: 1 }, hint: "Perhatikan variabel 'y'. Di satu persamaan ia -y, dan di lainnya +y. Langsung jumlahkan (eliminasi)!" }
];

export const cutscenes = {
    afterCase5: "Jadi... detektif kecil sudah memecahkan teka-teki pemanasanku. Menggemaskan.\n\nTapi Babak Pertama sudah berakhir. Bersiaplah, karena permainanku yang sesungguhnya akan segera dimulai.\n\n- Dalang Persamaan"
};